### ISSUE TITLE
Allow for multiple filters to be declared declaratively

### ISSUE THREAD

**Issue by chee** [Financial-Times/o-table#248] opened 2021-03-25 16:00 UTC
https://github.com/Financial-Times/o-table/blob/v8.1.4/src/js/Tables/BaseTable.js#L98

Not sure if we have a good reason for using `querySelector` here and only allowing one filter to exist on the page?
@balfourd has a use case where it would be helpful for us to allow for multiple filters defined in the dom this way

**Comment by chee** [comment] 2021-03-25 16:01
i believe they can already do it programatically by using the [filter](https://github.com/Financial-Times/o-table/blob/v8.1.4/src/js/Tables/BaseTable.js#L322-L327) function with a callback param

**Comment by notlee** [comment] 2021-03-25 16:17
>Not sure if we have a good reason for using querySelector here and only allowing one filter to exist on the page?

There are other places which would need to be updated in addition to the querySelector, like this line which re-applies the filter after rows update:
https://github.com/Financial-Times/o-table/blob/3e9251646d182a064406ecbcbfb93d8edf670e48/src/js/Tables/BaseTable.js#L154

>i believe they can already do it programatically by using the filter function with a callback param
I believe that's correct

**Comment by notlee** [comment] 2021-03-25 16:18
This is a duplicate of https://github.com/Financial-Times/o-table/issues/164 shall we close this one for that?

**Closed** 2021-03-25 16:19 UTC
Labels: component
